"""Client adapter manifest for reuse-first native control-plane clients."""
from __future__ import annotations

import json
from typing import Any

from .methodology_dispatch import METHODOLOGY_DISPATCH


def build_visual_client_manifest() -> dict[str, Any]:
    """Describe the default-read-only contract the secondary native client can consume."""
    endpoints = [
        {
            "id": "client-launch-plan",
            "path": "/client-plan.json",
            "method": "GET",
            "contract": "local_agent_client_launch_plan",
            "object_types": ["ClientLaunch", "Project", "ProviderBinding", "Agent", "DevFrameSession", "Gate", "Action"],
            "mutates": False,
            "description": "Zero-config secondary native-client launch plan, reuse boundary, endpoint map, and dashboard support summary around the primary devframe code product.",
        },
        {
            "id": "t3-bridge-bundle",
            "path": "/t3-bridge.json",
            "method": "GET",
            "contract": "t3_code_local_bridge_bundle",
            "object_types": ["T3Bridge", "ClientLaunch", "Project", "DevFrameSession"],
            "mutates": False,
            "description": "Installable T3 Code native-client bridge bundle with env values, generated source files, and wiring instructions.",
        },
        {
            "id": "visual-state",
            "path": "/state.json",
            "method": "GET",
            "contract": "visual_control_plane_state",
            "object_types": [
                "Project",
                "ProviderBinding",
                "Agent",
                "DevFrameSession",
                "Run",
                "Gate",
                "Decision",
                "Action",
            ],
            "mutates": False,
            "description": "Full governed read model for project, agent, run, evidence, gate, and action views.",
        },
        {
            "id": "t3-shell",
            "path": "/t3-shell.json",
            "method": "GET",
            "contract": "t3_client_shell",
            "object_types": ["Project", "ProviderBinding", "Agent", "DevFrameSession", "Gate", "Action"],
            "mutates": False,
            "description": "Secondary T3 Code native-client project/thread shell snapshot with DevFrame gate and action overlays around the main devframe code workflow.",
        },
        {
            "id": "t3-environment-descriptor",
            "path": "/.well-known/t3/environment",
            "method": "GET",
            "contract": "t3_execution_environment_descriptor",
            "object_types": ["T3Environment"],
            "mutates": False,
            "description": "Minimal T3 primary-environment descriptor for local DevFrame bootstrap.",
        },
        {
            "id": "t3-auth-session",
            "path": "/api/auth/session",
            "method": "GET",
            "contract": "t3_readonly_auth_session",
            "object_types": ["T3AuthSession", "T3Environment"],
            "mutates": False,
            "description": "Loopback-only read session descriptor that lets the T3 Code native client load DevFrame's read-only shell.",
        },
        {
            "id": "t3-projects",
            "path": "/api/t3/projects",
            "method": "GET",
            "contract": "t3_project_options",
            "object_types": ["Project"],
            "mutates": False,
            "description": "Loopback read of registered projects for coordinator goal creation and project binding selection.",
        },
        {
            "id": "t3-conversation-model",
            "path": "/api/t3/conversation-model",
            "method": "GET",
            "contract": "t3_conversation_model",
            "object_types": ["DevFrameSession", "Project"],
            "mutates": False,
            "description": "Loopback read of conversation kinds, the global coordinator thread id, and the goal project-binding requirement.",
        },
        {
            "id": "t3-coordinator-entry",
            "path": "/api/t3/coordinator-entry",
            "method": "GET",
            "contract": "t3_coordinator_shell_entry",
            "object_types": ["DevFrameSession", "Project", "Action", "Gate"],
            "mutates": False,
            "description": "One-call read model for the RD-Code Global Coordinator entry: sorted shell snapshot, global coordinator thread, goal conversations, project picker options, and goal-start readiness.",
        },
        {
            "id": "sessions",
            "path": "/sessions.json",
            "method": "GET",
            "contract": "public_session_summaries",
            "object_types": ["DevFrameSession"],
            "mutates": False,
            "description": "Public session list for conversation workbench and session detail navigation.",
        },
        {
            "id": "session-detail",
            "path": "/sessions/{session_id}.json",
            "method": "GET",
            "contract": "public_session_detail",
            "object_types": ["DevFrameSession"],
            "mutates": False,
            "description": "Exact-match public session detail projection; missing sessions return 404.",
        },
        {
            "id": "web-ai-sessions",
            "path": "/web-ai-sessions.json",
            "method": "GET",
            "contract": "public_session_summaries",
            "object_types": ["DevFrameSession", "ProviderBinding", "Agent"],
            "mutates": False,
            "description": "Summary-only browser AI session projections; raw transcripts and browser profiles are excluded.",
        },
        {
            "id": "action-queue",
            "path": "/actions.json",
            "method": "GET",
            "contract": "next_actions",
            "object_types": ["Action", "Gate", "Run", "Decision", "DevFrameSession"],
            "mutates": False,
            "description": "Filterable queue for manual resume, review, and future gated client actions.",
        },
        {
            "id": "action-handoff",
            "path": "/actions.md",
            "method": "GET",
            "contract": "action_queue_markdown",
            "object_types": ["Action"],
            "mutates": False,
            "description": "Markdown handoff for humans or web AI sessions when direct automation is not allowed.",
        },
        {
            "id": "go-dispatch-page",
            "path": "/go/dispatch",
            "method": "GET",
            "contract": "go_dispatch_page",
            "object_types": ["Project", "Run", "Action"],
            "mutates": False,
            "description": "Auxiliary loopback form for preparing or executing /go coding-agent dispatches when the lightweight web dashboard is used.",
        },
        {
            "id": "go-dispatch-submit",
            "path": "/go/dispatch",
            "method": "POST",
            "contract": "go_dispatch_request",
            "object_types": ["Project", "Run", "Action"],
            "mutates": True,
            "description": "Loopback-only, same-origin /go dispatch request that prepares packets or starts coding-agent shards.",
        },
        {
            "id": "controlled-action-page",
            "path": "/actions/open",
            "method": "GET",
            "contract": "controlled_action_page",
            "object_types": ["Action"],
            "mutates": False,
            "description": "Human-readable local action page linked from T3 message and plan Markdown.",
        },
        {
            "id": "controlled-action-execute",
            "path": "/actions/execute",
            "method": "POST",
            "contract": "controlled_action_execution",
            "object_types": ["Action", "Run", "DevFrameSession"],
            "mutates": True,
            "description": "Loopback-only, confirm-gated execution entry for queued DevFrame Code go-runs and Web GPT task-intake dispatch.",
        },
        {
            "id": "t3-approval-response",
            "path": "/api/t3/approval-response",
            "method": "POST",
            "contract": "t3_approval_response",
            "object_types": ["Action", "Run", "DevFrameSession"],
            "mutates": True,
            "description": "Loopback-only approval callback used by T3 approval.requested activities to execute controlled actions.",
        },
        {
            "id": "t3-writeback-propose",
            "path": "/api/t3/writeback-propose",
            "method": "POST",
            "contract": "t3_writeback_proposal",
            "object_types": ["Project", "DevFrameSession"],
            "mutates": True,
            "description": "Loopback-only write-back proposal staging; nothing is written until a human approves the proposal via /api/t3/approval-response.",
        },
        {
            "id": "t3-cluster-targets",
            "path": "/api/t3/cluster-targets",
            "method": "GET",
            "contract": "t3_cluster_targets",
            "object_types": ["Agent"],
            "mutates": False,
            "description": "Loopback read of the cluster @-mention targets (coordinator/主控, recorded agents, default worker roster) the editor composer can offer.",
        },
        {
            "id": "t3-cluster-runs",
            "path": "/api/t3/cluster-runs",
            "method": "GET",
            "contract": "t3_cluster_runs",
            "object_types": ["Run", "Agent"],
            "mutates": False,
            "description": "Loopback read of cluster run progress (status + summary per goal) for the editor's coordinator overview panel; monitoring only.",
        },
        {
            "id": "t3-cluster-run-events",
            "path": "/api/t3/cluster-run-events",
            "method": "GET",
            "contract": "t3_cluster_run_events",
            "object_types": ["Run", "Agent"],
            "mutates": False,
            "description": "Loopback read of one cluster run's coordinator<->agent message timeline plus its per-agent summary cards; monitoring only.",
        },
        {
            "id": "t3-cluster-run-agent",
            "path": "/api/t3/cluster-run-agent",
            "method": "GET",
            "contract": "t3_cluster_run_agent",
            "object_types": ["Agent", "Run"],
            "mutates": False,
            "description": "Loopback read of one agent's detailed execution view (status, changed files, tokens, tool calls, ExecutionReport) for the agent drill-down; monitoring only.",
        },
        {
            "id": "t3-cluster-roster",
            "path": "/api/t3/cluster-roster",
            "method": "GET",
            "contract": "t3_cluster_roster",
            "object_types": ["Agent"],
            "mutates": False,
            "description": "Loopback read of the user-customizable cluster agent roster (falls back to the default roster when none is configured).",
        },
        {
            "id": "t3-skills",
            "path": "/api/t3/skills",
            "method": "GET",
            "contract": "t3_skills",
            "object_types": ["Skill"],
            "mutates": False,
            "description": "Loopback read of methodology skills for the visual editor: read-only built-in skills plus user-created custom skills.",
        },
        {
            "id": "t3-rules",
            "path": "/api/t3/rules",
            "method": "GET",
            "contract": "t3_rules",
            "object_types": ["Rule"],
            "mutates": False,
            "description": "Loopback read of governance rules for the visual editor: machine-readable built-in rules (parsed from rules/*.md) plus user-created custom rules.",
        },
        {
            "id": "t3-run-defaults",
            "path": "/api/t3/run-defaults",
            "method": "GET",
            "contract": "t3_run_defaults",
            "object_types": ["RunDefaults"],
            "mutates": False,
            "description": "Loopback read of run defaults (worker count, model, default methodology) as the four-layer built-in/global/project/effective view for the visual editor.",
        },
        {
            "id": "t3-memory",
            "path": "/api/t3/memory",
            "method": "GET",
            "contract": "t3_memory",
            "object_types": ["Preferences", "ProjectMemory"],
            "mutates": False,
            "description": "Loopback read of global preferences and project memory for the visual editor (two distinct layers; project memory requires a project id).",
        },
        {
            "id": "t3-cluster-run",
            "path": "/api/t3/cluster-run",
            "method": "POST",
            "contract": "t3_cluster_run",
            "object_types": ["Agent", "Run", "Project"],
            "mutates": True,
            "description": "Loopback-only cluster run start for a &-mentioned target. Authorized by the human's inline confirm in the conversation; starts a project-coordinator run. No dashboard approval is involved.",
        },
        {
            "id": "t3-cluster-roster-save",
            "path": "/api/t3/cluster-roster",
            "method": "POST",
            "contract": "t3_cluster_roster_save",
            "object_types": ["Agent"],
            "mutates": True,
            "description": "Loopback-only save of the user-customizable cluster agent roster (the visual customization of which agents the coordinator can dispatch to).",
        },
        {
            "id": "t3-skills-save",
            "path": "/api/t3/skills",
            "method": "POST",
            "contract": "t3_skills_save",
            "object_types": ["Skill"],
            "mutates": True,
            "description": "Loopback-only save of user-created methodology skills (the visual creation/editing of complete skill units: identity + behavior profile).",
        },
        {
            "id": "t3-rules-save",
            "path": "/api/t3/rules",
            "method": "POST",
            "contract": "t3_rules_save",
            "object_types": ["Rule"],
            "mutates": True,
            "description": "Loopback-only save of user-created governance rules (the visual editing of machine-readable rule records).",
        },
        {
            "id": "t3-run-defaults-save",
            "path": "/api/t3/run-defaults",
            "method": "POST",
            "contract": "t3_run_defaults_save",
            "object_types": ["RunDefaults"],
            "mutates": True,
            "description": "Loopback-only save of run defaults at a chosen scope (global or project).",
        },
        {
            "id": "t3-memory-save",
            "path": "/api/t3/memory",
            "method": "POST",
            "contract": "t3_memory_save",
            "object_types": ["Preferences", "ProjectMemory"],
            "mutates": True,
            "description": "Loopback-only save of global preferences or project memory at the targeted layer.",
        },
        {
            "id": "t3-cluster-run-delete",
            "path": "/api/t3/cluster-run-delete",
            "method": "POST",
            "contract": "t3_cluster_run_delete",
            "object_types": ["Run"],
            "mutates": True,
            "description": "Loopback-only delete of a recorded cluster run from the coordinator overview.",
        },
        {
            "id": "t3-cluster-run-rename",
            "path": "/api/t3/cluster-run-rename",
            "method": "POST",
            "contract": "t3_cluster_run_rename",
            "object_types": ["Run"],
            "mutates": True,
            "description": "Loopback-only rename of a recorded cluster run's goal/title in the coordinator overview.",
        },
    ]
    return {
        "version": 1,
        "name": "devframe-local-agent-client-adapter",
        "reuse": {
            "client": "t3code",
            "client_role": "primary-native-client-shell",
            "executor": "opencode",
            "executor_role": "local-coding-agent-runtime",
            "devframe_role": "governance-protocol-and-read-model",
        },
        "transport": {
            "kind": "same-origin-http",
            "authority": "loopback",
            "client_plan_endpoint": "/client-plan.json",
            "t3_bridge_endpoint": "/t3-bridge.json",
            "t3_environment_endpoint": "/.well-known/t3/environment",
            "t3_auth_session_endpoint": "/api/auth/session",
            "state_endpoint": "/state.json",
            "shell_endpoint": "/t3-shell.json",
            "manifest_endpoint": "/client-manifest.json",
        },
        "endpoints": endpoints,
        "surface_mappings": [
            {
                "id": "client-launch",
                "client_surface": "zero-config-primary-native-client-entry",
                "source_endpoint": "/client-plan.json",
                "object_types": ["ClientLaunch"],
                "status": "ready",
            },
            {
                "id": "t3-bridge",
                "client_surface": "t3-code-local-bridge-installer",
                "source_endpoint": "/t3-bridge.json",
                "object_types": ["T3Bridge", "ClientLaunch"],
                "status": "ready",
            },
            {
                "id": "project-workbench",
                "client_surface": "native-project-list-and-active-project",
                "source_endpoint": "/t3-shell.json",
                "object_types": ["Project", "Run", "Gate", "Action"],
                "status": "ready",
            },
            {
                "id": "agent-registry",
                "client_surface": "native-agent-sidebar-or-registry-pane",
                "source_endpoint": "/state.json",
                "object_types": ["Agent", "ProviderBinding"],
                "status": "ready",
            },
            {
                "id": "session-workbench",
                "client_surface": "native-conversation-list-and-session-detail",
                "source_endpoint": "/t3-shell.json",
                "object_types": ["DevFrameSession"],
                "status": "ready",
            },
            {
                "id": "action-queue",
                "client_surface": "gated-action-queue",
                "source_endpoint": "/actions.json",
                "object_types": ["Action", "Gate", "Run", "Decision"],
                "status": "ready",
            },
            {
                "id": "go-dispatch",
                "client_surface": "auxiliary-dashboard-project-level-go-dispatch",
                "source_endpoint": "/go/dispatch",
                "object_types": ["Project", "Run", "Action"],
                "status": "ready",
            },
            {
                "id": "controlled-action-execution",
                "client_surface": "local-action-open-and-confirm",
                "source_endpoint": "/actions/open",
                "object_types": ["Action", "Run"],
                "status": "ready",
            },
            {
                "id": "web-gpt-review-gate",
                "client_surface": "external-web-gpt-review-gate",
                "source_endpoint": "/actions.md",
                "object_types": ["Action", "Gate", "DevFrameSession"],
                "status": "ready",
            },
            {
                "id": "opencode-executor-events",
                "client_surface": "executor-output-and-diff-pane",
                "source_endpoint": "/state.json",
                "object_types": ["DevFrameSession", "Run"],
                "status": "adapter-required",
            },
        ],
        "write_policy": {
            "default": "read-only",
            "blocked_methods": ["PUT", "PATCH", "DELETE"],
            "allowed_mutation_endpoints": [
                {
                    "method": "POST",
                    "path": "/go/dispatch",
                    "requires": ["loopback-client", "same-origin", "registered-project-root"],
                },
                {
                    "method": "POST",
                    "path": "/actions/execute",
                    "requires": ["loopback-client", "confirm=execute", "queued-go-run-or-web-gpt-task-intake-action"],
                },
                {
                    "method": "POST",
                    "path": "/api/t3/approval-response",
                    "requires": ["loopback-client", "loopback-origin", "approval.requested", "approve-or-reject"],
                },
                {
                    "method": "POST",
                    "path": "/api/t3/writeback-propose",
                    "requires": ["loopback-client", "loopback-origin", "registered-project-root", "human-approval-before-write"],
                },
                {
                    "method": "POST",
                    "path": "/api/t3/cluster-run",
                    "requires": ["loopback-client", "loopback-origin", "valid-cluster-target", "human-inline-confirm-in-conversation"],
                },
                {
                    "method": "POST",
                    "path": "/api/t3/cluster-roster",
                    "requires": ["loopback-client", "loopback-origin", "validated-roster"],
                },
                {
                    "method": "POST",
                    "path": "/api/t3/skills",
                    "requires": ["loopback-client", "loopback-origin", "validated-skills"],
                },
                {
                    "method": "POST",
                    "path": "/api/t3/rules",
                    "requires": ["loopback-client", "loopback-origin", "validated-rules"],
                },
                {
                    "method": "POST",
                    "path": "/api/t3/run-defaults",
                    "requires": ["loopback-client", "loopback-origin", "validated-run-defaults"],
                },
                {
                    "method": "POST",
                    "path": "/api/t3/memory",
                    "requires": ["loopback-client", "loopback-origin", "validated-memory"],
                },
                {
                    "method": "POST",
                    "path": "/api/t3/cluster-run-delete",
                    "requires": ["loopback-client", "loopback-origin", "existing-run"],
                },
                {
                    "method": "POST",
                    "path": "/api/t3/cluster-run-rename",
                    "requires": ["loopback-client", "loopback-origin", "existing-run", "non-empty-goal"],
                }
            ],
            "mutation_status": "human-gated-local-actions",
            "human_gate_required_for": [
                "execute_worker",
                "reply_to_provider",
                "read_browser_profile",
                "persist_raw_transcript",
                "apply_patch",
                "publish_or_deploy",
            ],
        },
        "supported_methodologies": [
            {
                "skill_id": entry["skill_id"],
                "title": entry["title"],
                "display_label": entry.get("display_label") or entry["title"],
                "triggers": list(dict.fromkeys(entry.get("triggers", []))),
                "source_kind": entry.get("source_kind", ""),
                **({"require_red_green_evidence": True} if entry.get("require_red_green_evidence") else {}),
                **({"profiles": entry["profiles"]} if entry.get("profiles") else {}),
            }
            for entry in METHODOLOGY_DISPATCH.values()
        ],
        "governance": {
            "reconReceipt": "docs/status/recon-receipt-local-agent-client-mainline.md",
            "rkrRulePath": "rules/recon.md",
            "reuseAssessment": "docs/status/t3code-client-mainline-reuse-assessment.md",
            "primaryClientDecision": "devframe code: primary product loop; T3Code: secondary native-client shell; DevFrame owns governance",
            "workerDecision": "OpenCode: local coding-agent worker runtime",
            "webAiAdapterDecision": "CodexPro/DevSpace: Web AI MCP bridge patterns; ZIP/report is fallback only",
            "nextApprovedSlice": "Expose Recon Receipt and reuse decision in client launch plan and visual client manifest",
        },
    }


def render_visual_client_manifest_json(manifest: dict[str, Any] | None = None) -> str:
    return json.dumps(manifest or build_visual_client_manifest(), indent=2, ensure_ascii=True)
