"""Client adapter manifest for reuse-first native control-plane clients."""
from __future__ import annotations

import json
from typing import Any


def build_visual_client_manifest() -> dict[str, Any]:
    """Describe the default-read-only contract the primary native client can consume."""
    endpoints = [
        {
            "id": "client-launch-plan",
            "path": "/client-plan.json",
            "method": "GET",
            "contract": "local_agent_client_launch_plan",
            "object_types": ["ClientLaunch", "Project", "ProviderBinding", "Agent", "DevFrameSession", "Gate", "Action"],
            "mutates": False,
            "description": "Zero-config native-client launch plan, reuse boundary, endpoint map, and dashboard support summary.",
        },
        {
            "id": "t3-bridge-bundle",
            "path": "/t3-bridge.json",
            "method": "GET",
            "contract": "t3_code_local_bridge_bundle",
            "object_types": ["T3Bridge", "ClientLaunch", "Project", "DevFrameSession"],
            "mutates": False,
            "description": "Installable T3 Code native-client bridge bundle with env values, generated source files, and wiring instructions.",
        },
        {
            "id": "visual-state",
            "path": "/state.json",
            "method": "GET",
            "contract": "visual_control_plane_state",
            "object_types": [
                "Project",
                "ProviderBinding",
                "Agent",
                "DevFrameSession",
                "Run",
                "Gate",
                "Decision",
                "Action",
            ],
            "mutates": False,
            "description": "Full governed read model for project, agent, run, evidence, gate, and action views.",
        },
        {
            "id": "t3-shell",
            "path": "/t3-shell.json",
            "method": "GET",
            "contract": "t3_client_shell",
            "object_types": ["Project", "ProviderBinding", "Agent", "DevFrameSession", "Gate", "Action"],
            "mutates": False,
            "description": "Primary T3 Code native-client project/thread shell snapshot with DevFrame gate and action overlays.",
        },
        {
            "id": "t3-environment-descriptor",
            "path": "/.well-known/t3/environment",
            "method": "GET",
            "contract": "t3_execution_environment_descriptor",
            "object_types": ["T3Environment"],
            "mutates": False,
            "description": "Minimal T3 primary-environment descriptor for local DevFrame bootstrap.",
        },
        {
            "id": "t3-auth-session",
            "path": "/api/auth/session",
            "method": "GET",
            "contract": "t3_readonly_auth_session",
            "object_types": ["T3AuthSession", "T3Environment"],
            "mutates": False,
            "description": "Loopback-only read session descriptor that lets the T3 Code native client load DevFrame's read-only shell.",
        },
        {
            "id": "sessions",
            "path": "/sessions.json",
            "method": "GET",
            "contract": "public_session_summaries",
            "object_types": ["DevFrameSession"],
            "mutates": False,
            "description": "Public session list for conversation workbench and session detail navigation.",
        },
        {
            "id": "web-ai-sessions",
            "path": "/web-ai-sessions.json",
            "method": "GET",
            "contract": "public_session_summaries",
            "object_types": ["DevFrameSession", "ProviderBinding", "Agent"],
            "mutates": False,
            "description": "Summary-only browser AI session projections; raw transcripts and browser profiles are excluded.",
        },
        {
            "id": "action-queue",
            "path": "/actions.json",
            "method": "GET",
            "contract": "next_actions",
            "object_types": ["Action", "Gate", "Run", "Decision", "DevFrameSession"],
            "mutates": False,
            "description": "Filterable queue for manual resume, review, and future gated client actions.",
        },
        {
            "id": "action-handoff",
            "path": "/actions.md",
            "method": "GET",
            "contract": "action_queue_markdown",
            "object_types": ["Action"],
            "mutates": False,
            "description": "Markdown handoff for humans or web AI sessions when direct automation is not allowed.",
        },
        {
            "id": "go-dispatch-page",
            "path": "/go/dispatch",
            "method": "GET",
            "contract": "go_dispatch_page",
            "object_types": ["Project", "Run", "Action"],
            "mutates": False,
            "description": "Auxiliary loopback form for preparing or executing /go coding-agent dispatches when the lightweight web dashboard is used.",
        },
        {
            "id": "go-dispatch-submit",
            "path": "/go/dispatch",
            "method": "POST",
            "contract": "go_dispatch_request",
            "object_types": ["Project", "Run", "Action"],
            "mutates": True,
            "description": "Loopback-only, same-origin /go dispatch request that prepares packets or starts coding-agent shards.",
        },
        {
            "id": "controlled-action-page",
            "path": "/actions/open",
            "method": "GET",
            "contract": "controlled_action_page",
            "object_types": ["Action"],
            "mutates": False,
            "description": "Human-readable local action page linked from T3 message and plan Markdown.",
        },
        {
            "id": "controlled-action-execute",
            "path": "/actions/execute",
            "method": "POST",
            "contract": "controlled_action_execution",
            "object_types": ["Action", "Run", "DevFrameSession"],
            "mutates": True,
            "description": "Loopback-only, confirm-gated execution entry for queued DevFrame Code go-runs and Web GPT task-intake dispatch.",
        },
        {
            "id": "t3-approval-response",
            "path": "/api/t3/approval-response",
            "method": "POST",
            "contract": "t3_approval_response",
            "object_types": ["Action", "Run", "DevFrameSession"],
            "mutates": True,
            "description": "Loopback-only approval callback used by T3 approval.requested activities to execute controlled actions.",
        },
    ]
    return {
        "version": 1,
        "name": "devframe-local-agent-client-adapter",
        "reuse": {
            "client": "t3code",
            "client_role": "primary-native-client-shell",
            "executor": "opencode",
            "executor_role": "local-coding-agent-runtime",
            "devframe_role": "governance-protocol-and-read-model",
        },
        "transport": {
            "kind": "same-origin-http",
            "authority": "loopback",
            "client_plan_endpoint": "/client-plan.json",
            "t3_bridge_endpoint": "/t3-bridge.json",
            "t3_environment_endpoint": "/.well-known/t3/environment",
            "t3_auth_session_endpoint": "/api/auth/session",
            "state_endpoint": "/state.json",
            "shell_endpoint": "/t3-shell.json",
            "manifest_endpoint": "/client-manifest.json",
        },
        "endpoints": endpoints,
        "surface_mappings": [
            {
                "id": "client-launch",
                "client_surface": "zero-config-primary-native-client-entry",
                "source_endpoint": "/client-plan.json",
                "object_types": ["ClientLaunch"],
                "status": "ready",
            },
            {
                "id": "t3-bridge",
                "client_surface": "t3-code-local-bridge-installer",
                "source_endpoint": "/t3-bridge.json",
                "object_types": ["T3Bridge", "ClientLaunch"],
                "status": "ready",
            },
            {
                "id": "project-workbench",
                "client_surface": "native-project-list-and-active-project",
                "source_endpoint": "/t3-shell.json",
                "object_types": ["Project", "Run", "Gate", "Action"],
                "status": "ready",
            },
            {
                "id": "agent-registry",
                "client_surface": "native-agent-sidebar-or-registry-pane",
                "source_endpoint": "/state.json",
                "object_types": ["Agent", "ProviderBinding"],
                "status": "ready",
            },
            {
                "id": "session-workbench",
                "client_surface": "native-conversation-list-and-session-detail",
                "source_endpoint": "/t3-shell.json",
                "object_types": ["DevFrameSession"],
                "status": "ready",
            },
            {
                "id": "action-queue",
                "client_surface": "gated-action-queue",
                "source_endpoint": "/actions.json",
                "object_types": ["Action", "Gate", "Run", "Decision"],
                "status": "ready",
            },
            {
                "id": "go-dispatch",
                "client_surface": "auxiliary-dashboard-project-level-go-dispatch",
                "source_endpoint": "/go/dispatch",
                "object_types": ["Project", "Run", "Action"],
                "status": "ready",
            },
            {
                "id": "controlled-action-execution",
                "client_surface": "local-action-open-and-confirm",
                "source_endpoint": "/actions/open",
                "object_types": ["Action", "Run"],
                "status": "ready",
            },
            {
                "id": "web-gpt-review-gate",
                "client_surface": "external-web-gpt-review-gate",
                "source_endpoint": "/actions.md",
                "object_types": ["Action", "Gate", "DevFrameSession"],
                "status": "ready",
            },
            {
                "id": "opencode-executor-events",
                "client_surface": "executor-output-and-diff-pane",
                "source_endpoint": "/state.json",
                "object_types": ["DevFrameSession", "Run"],
                "status": "adapter-required",
            },
        ],
        "write_policy": {
            "default": "read-only",
            "blocked_methods": ["PUT", "PATCH", "DELETE"],
            "allowed_mutation_endpoints": [
                {
                    "method": "POST",
                    "path": "/go/dispatch",
                    "requires": ["loopback-client", "same-origin", "registered-project-root"],
                },
                {
                    "method": "POST",
                    "path": "/actions/execute",
                    "requires": ["loopback-client", "confirm=execute", "queued-go-run-or-web-gpt-task-intake-action"],
                },
                {
                    "method": "POST",
                    "path": "/api/t3/approval-response",
                    "requires": ["loopback-client", "loopback-origin", "approval.requested", "approve-or-reject"],
                }
            ],
            "mutation_status": "human-gated-local-actions",
            "human_gate_required_for": [
                "execute_worker",
                "reply_to_provider",
                "read_browser_profile",
                "persist_raw_transcript",
                "apply_patch",
                "publish_or_deploy",
            ],
        },
        "governance": {
            "reconReceipt": "docs/status/recon-receipt-local-agent-client-mainline.md",
            "rkrRulePath": "rules/recon.md",
            "reuseAssessment": "docs/status/t3code-client-mainline-reuse-assessment.md",
            "primaryClientDecision": "T3Code: primary native-client shell; DevFrame owns governance",
            "workerDecision": "OpenCode: local coding-agent worker runtime",
            "webAiAdapterDecision": "CodexPro/DevSpace: Web AI MCP bridge patterns; ZIP/report is fallback only",
            "nextApprovedSlice": "Expose Recon Receipt and reuse decision in client launch plan and visual client manifest",
        },
    }


def render_visual_client_manifest_json(manifest: dict[str, Any] | None = None) -> str:
    return json.dumps(manifest or build_visual_client_manifest(), indent=2, ensure_ascii=True)
