"""Phase 1C: prepare-only review packet skeleton.

Emits a sample review-governance packet from a work-item description.
Does not write runtime state, run coordinator work, or create authority.
Output goes to stdout or a user-specified file.
"""
from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def generate_review_packet(
    work_item_id: str,
    intent: str,
    project_id: str = "proj-review-demo",
) -> dict:
    """Generate a sample review-governance packet.

    All IDs are deterministic from inputs. No runtime state is touched.
    The packet is in draft/ready state — no decisions or evidence yet,
    because authority comes from a human or agent run, not from prepare.
    """
    run_id = f"run-{work_item_id.replace('wi-', '')}"
    ctx_id = f"artifact-ctx-{work_item_id.replace('wi-', '')}"
    principal_human = "principal-human-1"
    principal_agent = "principal-agent-1"

    return {
        "schema_version": "0.1",
        "project": {
            "id": project_id,
            "display_name": "Review Governance Kernel Demo",
            "scope": intent[:80],
            "owner_principal_id": principal_human,
            "policy_profile": "evidence_first",
        },
        "work_item": {
            "id": work_item_id,
            "project_id": project_id,
            "kind": "review",
            "intent": intent,
            "status": "ready",
            "input_context_artifact_id": ctx_id,
        },
        "document_revisions": [],
        "runs": [
            {
                "id": run_id,
                "project_id": project_id,
                "work_item_id": work_item_id,
                "principal_id": principal_agent,
                "tool_boundary": "agent-runtime",
                "input_context_artifact_id": ctx_id,
                "status": "prepared",
                "claimed_result": "pending",
            }
        ],
        "artifacts": [
            {
                "id": ctx_id,
                "project_id": project_id,
                "kind": "context_snapshot",
                "producer_ref": "system",
                "content_ref": "embedded",
                "immutable": True,
                "source_refs": [f"doc://REVIEW_SPEC/{work_item_id}"],
                "selected_items": [],
                "omitted_required_items": [],
                "freshness": _now_iso(),
                "authority_level": "canonical",
                "redaction_summary": "no secrets required",
                "selection_rationale": "auto-generated by rdreview prepare",
                "token_budget": 2000,
                "content_hash": "a" * 64,
                "knowledge_gap_assessment": "none",
                "required_knowledge": [],
                "assumption_claims": [],
                "checked_sources": ["doc://REVIEW_SPEC"],
                "unresolved_gaps": [],
            }
        ],
        "evidence": [],
        "decisions": [],
        "principals": [
            {
                "id": principal_human,
                "kind": "human",
                "display_name": "Reviewer",
                "authority_scope": "full",
            },
            {
                "id": principal_agent,
                "kind": "agent",
                "display_name": "Executor Agent",
                "authority_scope": "read_write_within_scope",
            },
        ],
        "projection": {
            "work_item_id": work_item_id,
            "computed_status": "ready",
            "blocked_reason": "",
            "evidence_summary": {
                "total_evidence_count": 0,
                "supporting_count": 0,
                "rejecting_count": 0,
                "inconclusive_count": 0,
            },
            "decision_summary": {
                "review_outcome": "",
                "gate_outcome": "",
                "latest_decision_id": "",
            },
            "allowed_actions": ["view", "execute", "edit"],
        },
    }


def cmd_rdreview_prepare(
    work_item_id: str,
    intent: str,
    output: Optional[str] = None,
    project_id: str = "proj-review-demo",
) -> int:
    """Prepare a sample review packet. Writes to stdout or file."""
    packet = generate_review_packet(work_item_id, intent, project_id)
    payload = json.dumps(packet, indent=2, ensure_ascii=False)

    if output:
        Path(output).write_text(payload, encoding="utf-8")
        print(f"Review packet written to {output}")
    else:
        print(payload)
    return 0
